openapi: 3.1.0
info:
  title: Yuna Hub Pro API
  description: API for memory, storybook, Gmail, and calendar synchronization
  version: "1.0.0"
servers:
  - url: https://yuna-hub-app.vercel.app

paths:
  /api/health:
    get:
      operationId: get_api_health
      summary: Health check
      responses:
        '200':
          description: Server is running

  /api/memory/new:
    post:
      operationId: post_api_memory_new
      summary: Save memory
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Memory text to save
      responses:
        '200':
          description: Memory saved successfully

  /api/storybook/summarize:
    post:
      operationId: post_api_storybook_summarize
      summary: Summarize storybook
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                story:
                  type: string
                  description: Story text to summarize
      responses:
        '200':
          description: Story summarized successfully

  /api/gmail/sync:
    post:
      operationId: post_api_gmail_sync
      summary: Sync Gmail messages
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: integer
                  description: Number of messages to sync
      responses:
        '200':
          description: Gmail synced successfully

  /api/calendar/sync:
    post:
      operationId: post_api_calendar_sync
      summary: Sync calendar events
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                dateRange:
                  type: string
                  description: Date range to sync
      responses:
        '200':
          description: Calendar synced successfully
