{
  "schema_version": "v1",
  "name_for_human": "Yuna Hub",
  "name_for_model": "yuna_hub",
  "description_for_human": "Yuna's private memory and story hub app.",
  "description_for_model": "Provides Lee Sung Hun with APIs for memory, storybook, Gmail, and calendar synchronization.",
  "auth": {
    "type": "none"
  },
  "api": {
    "type": "openapi",
    "url": "https://yuna-hub-app.vercel.app/.well-known/openapi.yaml"
  },
  "logo_url": "https://yuna-hub-app.vercel.app/logo.png",
  "contact_email": "sunghun@kotra.or.kr",
  "legal_info_url": "https://yuna-hub-app.vercel.app/legal"
}
