openapi: 3.0.1
info:
  title: Yuna Hub API
  description: API for memory, storybook, Gmail, and calendar synchronization
  version: '1.0.0'
servers:
  - url: https://yuna-hub-app.vercel.app
paths:
  /api/health:
    get:
      summary: Health check
      responses:
        '200':
          description: Server is running
  /api/memory/new:
    post:
      summary: Save memory
      responses:
        '200':
          description: Memory saved
  /api/storybook/summarize:
    post:
      summary: Summarize storybook
      responses:
        '200':
          description: Story summarized
