openapi: 3.1.0
info:
  title: Yuna Hub API
  description: OpenAPI specification for Yuna Hub plugin.
  version: 1.0.0
servers:
  - url: https://yuna-hub-app.vercel.app
paths:
  /healthz:
    get:
      operationId: get_health
      summary: Health check endpoint
      responses:
        "200":
          description: OK
  /api/summarize-url:
    post:
      operationId: post_summarize_url
      summary: Summarize content from a given URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        "200":
          description: Summarization successful
