openapi: 3.1.0
info:
  title: YunaHub API
  version: "1.0.0"
servers:
  - url: https://YOUR_DOMAIN
paths:
  /healthz:
    get:
      summary: Health check
      responses: { "200": { description: ok } }
  /summarize-url:
    post:
      summary: Summarize a given URL content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: { url: { type: string } }
      responses:
        "200":
          description: summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  title: { type: string }
                  bullets:
                    type: array
                    items: { type: string }
  /calendar-daily:
    get:
      summary: Get daily calendar summary
      parameters:
        - in: query
          name: date
          schema: { type: string, example: "2025-10-07" }
      responses:
        "200":
          description: calendar summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  date: { type: string }
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        time: { type: string }
                        title: { type: string }
                        location: { type: string }
                        note: { type: string }
  /docs/search:
    get:
      summary: Search internal docs
      parameters:
        - in: query
          name: q
          schema: { type: string }
      responses:
        "200":
          description: search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        title: { type: string }
                        snippet: { type: string }
                        url: { type: string }
components: {}
