openapi: 3.1.0
info:
  title: Yuna Hub API
  version: "1.0.0"
servers:
  - url: https://YOUR_DOMAIN
paths:
  /api/summarize-url:
    post:
      summary: Summarize a web page by URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [url]
              properties:
                url:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  summary: { type: string }

  /api/docs/search:
    get:
      summary: Search documents
      parameters:
        - in: query
          name: q
          required: false
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        title: { type: string }
                        snippet: { type: string }
                        url: { type: string }

  /api/calendar-daily:
    get:
      summary: Get daily calendar
      parameters:
        - in: query
          name: date
          required: false
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  date: { type: string }
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        time: { type: string }
                        title: { type: string }
