openapi: 3.1.0
info:
  title: Yuna Hub API
  description: OpenAPI specification for Yuna Hub plugin (Pro version with memory, storybook, Gmail sync)
  version: 2.0.0
servers:
  - url: https://yuna-hub-app.vercel.app

paths:
  /healthz:
    get:
      operationId: get_health
      summary: Health check endpoint
      responses:
        "200":
          description: OK

  /api/summarize-url:
    post:
      operationId: post_summarize_url
      summary: Summarize content from a given URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        "200":
          description: Summarization successful

  /api/memory/save:
    post:
      operationId: post_memory_save
      summary: Save memory entry for the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        "200":
          description: Memory saved successfully

  /api/storybook/summarize:
    post:
      operationId: post_storybook_summarize
      summary: Summarize and store storybook text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        "200":
          description: Storybook summarized successfully

  /api/gmail/sync:
    post:
      operationId: post_gmail_sync
      summary: Sync Gmail messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                label:
                  type: string
      responses:
        "200":
          description: Gmail synced successfully
