openapi: 3.1.0
info:
  title: Yuna Hub API
  version: 1.0.0
servers:
  - url: https://your-domain.com
paths:
  /calendar:
    get:
      operationId: getCalendar
      summary: 캘린더 일정 가져오기
      responses:
        '200':
          description: 일정 리스트
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: string

  /docs:
    get:
      operationId: getDocuments
      summary: 문서 리스트 가져오기
      responses:
        '200':
          description: 문서 리스트
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: string

  /summarize:
    post:
      operationId: summarizeText
      summary: 입력 텍스트 요약
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: 요약 결과
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
