openapi: 3.0.1
info:
  title: Yuna Hub API
  description: OpenAPI specification for Yuna Hub plugin.
  version: 1.0.0
servers:
  - url: https://yuna-hub.vercel.app
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: OK
  /api/summarize:
    post:
      summary: Summarize content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Summary result
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
